In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

corpus=[
    "I like deep learning",
    "Deep learning models can learn word embeddings",
    "word embeddings capture semantic meaning of words",
    "Neural networks are powerful for NLP tasks",
    "Deep learning is connected to Machine learning",
    "I like Machine learning"
]
tokenizer=Tokenizer()
tokenizer.fit_on_texts(corpus)
word_index=tokenizer.word_index
print("Vocabulary:",word_index)
sequences=tokenizer.texts_to_sequences(corpus)
padded_sequences=pad_sequences(sequences, padding='post')
print("\nSequences:\n",sequences)
print("\nPadded Sequences:\n",padded_sequences)
vocab_size=len(word_index)+1
embedding_dim=8
max_length=padded_sequences.shape[1]
model=Sequential([
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_length),
    Flatten(),
    Dense(10,activation='relu'),
    Dense(5,activation='relu'),
    Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam',loss='binary_crossentropy')
labels=np.array([1,0,1,0,1,0])
model.fit(padded_sequences,labels,epochs=100,verbose=0)
embeddings=model.layers[0].get_weights()[0]
print("\nWord Embeddings shape:",embeddings.shape)
word="deep"
word_id=word_index[word]
print(f"Embeddings for word '{word}':\n", embeddings[word_id])
word="learning"
word_id=word_index[word]
print(f"Embeddings for word '{word}':\n", embeddings[word_id])
word="like"
word_id=word_index[word]
print(f"Embeddings for word '{word}':\n", embeddings[word_id])
word="machine"
word_id=word_index[word]
print(f"Embeddings for word '{word}':\n", embeddings[word_id])

Vocabulary: {'learning': 1, 'deep': 2, 'i': 3, 'like': 4, 'word': 5, 'embeddings': 6, 'machine': 7, 'models': 8, 'can': 9, 'learn': 10, 'capture': 11, 'semantic': 12, 'meaning': 13, 'of': 14, 'words': 15, 'neural': 16, 'networks': 17, 'are': 18, 'powerful': 19, 'for': 20, 'nlp': 21, 'tasks': 22, 'is': 23, 'connected': 24, 'to': 25}

Sequences:
 [[3, 4, 2, 1], [2, 1, 8, 9, 10, 5, 6], [5, 6, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22], [2, 1, 23, 24, 25, 7, 1], [3, 4, 7, 1]]

Padded Sequences:
 [[ 3  4  2  1  0  0  0]
 [ 2  1  8  9 10  5  6]
 [ 5  6 11 12 13 14 15]
 [16 17 18 19 20 21 22]
 [ 2  1 23 24 25  7  1]
 [ 3  4  7  1  0  0  0]]

Word Embeddings shape: (26, 8)
Embeddings for word 'deep':
 [ 0.17824908  0.05563224  0.01520201 -0.14738913 -0.08874751 -0.17654975
 -0.13873938 -0.06917589]
Embeddings for word 'learning':
 [-0.03005175  0.01274136  0.02556689 -0.00336228  0.06635194 -0.04496752
 -0.09646431 -0.02768891]
Embeddings for word 'like':
 [-0.0182297  -0.01738593 -0.00