In [9]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Flatten,Dense




documents=[
    "I love deep learning",
    "Deep Learning is amazing",
    "I enjoy machine learning",
    "Natural Language Processing is fun",
    "I dislike bugs in code",
    "Debugging code can be hard",
    "I hate syntax errors",
    "Errors make me frustrated"
]

labels=[1,1,1,1,0,0,0,0]

tokenizer=Tokenizer(num_words=50)
tokenizer.fit_on_texts(documents)

sequences=tokenizer.texts_to_sequences(documents)
print("Word Index:",tokenizer.word_index)
print("Sequences:",sequences)

X=pad_sequences(sequences,maxlen=6)
y=np.array(labels)
print("Padded Sequences:\n",X)

model=Sequential()
model.add(Embedding(input_dim=50,output_dim=8,input_length=6))
model.add(Flatten())
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X,y,epochs=20,verbose=1)

embeddings=model.layers[0].get_weights()[0]
print("\n Word Embeddings Shape:",embeddings.shape)

test_text=["I love coding"]
test_seq=tokenizer.texts_to_sequences(test_text)
test_pad=pad_sequences(test_seq,maxlen=6)
prediction=model.predict(test_pad)
print("predicition:",prediction)
print("class:","positive"if prediction>0.5 else "Negative")

Word Index: {'i': 1, 'learning': 2, 'deep': 3, 'is': 4, 'code': 5, 'errors': 6, 'love': 7, 'amazing': 8, 'enjoy': 9, 'machine': 10, 'natural': 11, 'language': 12, 'processing': 13, 'fun': 14, 'dislike': 15, 'bugs': 16, 'in': 17, 'debugging': 18, 'can': 19, 'be': 20, 'hard': 21, 'hate': 22, 'syntax': 23, 'make': 24, 'me': 25, 'frustrated': 26}
Sequences: [[1, 7, 3, 2], [3, 2, 4, 8], [1, 9, 10, 2], [11, 12, 13, 4, 14], [1, 15, 16, 17, 5], [18, 5, 19, 20, 21], [1, 22, 23, 6], [6, 24, 25, 26]]
Padded Sequences:
 [[ 0  0  1  7  3  2]
 [ 0  0  3  2  4  8]
 [ 0  0  1  9 10  2]
 [ 0 11 12 13  4 14]
 [ 0  1 15 16 17  5]
 [ 0 18  5 19 20 21]
 [ 0  0  1 22 23  6]
 [ 0  0  6 24 25 26]]
Epoch 1/20


/home/ailab/anaconda3/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 488ms/step - accuracy: 0.6250 - loss: 0.6916
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6250 - loss: 0.6890
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.6865
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.6840
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8750 - loss: 0.6814
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.6790
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.6766
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.6741
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.6716
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.6691
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.6666
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.6641
Epoch 13/20

In [18]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Flatten,Dense




documents=[
    "I love deep learning",
    "Deep Learning is amazing",
    "I enjoy machine learning",
    "Natural Language Processing is fun",
    "I dislike bugs in code",
    "Debugging code can be hard",
    "I hate syntax errors",
    "Errors make me frustrated"
]

labels=[1,1,1,1,1,1,0,0]

tokenizer=Tokenizer(num_words=50)
tokenizer.fit_on_texts(documents)

sequences=tokenizer.texts_to_sequences(documents)
print("Word Index:",tokenizer.word_index)
print("Sequences:",sequences)

X=pad_sequences(sequences,maxlen=6)
y=np.array(labels)
print("Padded Sequences:\n",X)

model=Sequential()
model.add(Embedding(input_dim=50, output_dim=16, input_length=6))
model.add(Flatten())
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X,y,epochs=20,verbose=1)

embeddings=model.layers[0].get_weights()[0]
print("\n Word Embeddings Shape:",embeddings.shape)

test_text = ["I love coding"]
test_seq=tokenizer.texts_to_sequences(test_text)
test_pad=pad_sequences(test_seq,maxlen=6)
prediction=model.predict(test_pad)
print("predicition:",prediction)
print("class:","positive"if prediction>0.5 else "Negative")

Word Index: {'i': 1, 'learning': 2, 'deep': 3, 'is': 4, 'code': 5, 'errors': 6, 'love': 7, 'amazing': 8, 'enjoy': 9, 'machine': 10, 'natural': 11, 'language': 12, 'processing': 13, 'fun': 14, 'dislike': 15, 'bugs': 16, 'in': 17, 'debugging': 18, 'can': 19, 'be': 20, 'hard': 21, 'hate': 22, 'syntax': 23, 'make': 24, 'me': 25, 'frustrated': 26}
Sequences: [[1, 7, 3, 2], [3, 2, 4, 8], [1, 9, 10, 2], [11, 12, 13, 4, 14], [1, 15, 16, 17, 5], [18, 5, 19, 20, 21], [1, 22, 23, 6], [6, 24, 25, 26]]
Padded Sequences:
 [[ 0  0  1  7  3  2]
 [ 0  0  3  2  4  8]
 [ 0  0  1  9 10  2]
 [ 0 11 12 13  4 14]
 [ 0  1 15 16 17  5]
 [ 0 18  5 19 20 21]
 [ 0  0  1 22 23  6]
 [ 0  0  6 24 25 26]]
Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 490ms/step - accuracy: 0.6250 - loss: 0.6892
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8750 - loss: 0.6850
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8750 - loss: 0.6804
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8750